version: '3.8'

services:
  mysql:
    image: mysql:8.0.39
    container_name: mysql_test_3
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - mysql-data:/var/lib/mysql
      - ./mysql-init:/docker-entrypoint-initdb.d
    networks:
      - extrahours_my-network
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build: ./api-gestion-horas-extras
    container_name: spring_boot_app_3
    ports:
      - "8080:8080"
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/${DB_NAME}
      SPRING_DATASOURCE_USERNAME: ${DB_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
    networks:
      - extrahours_my-network

#  frontend:
#    build: ./react-app
#    ports:
#      - "3000:3000"
#    depends_on:
#      - backend
#    networks:
#      - extrahours_my-network

volumes:
  mysql-data:


networks:
  extrahours_my-network:
    driver: bridge
